spring:
  application:
    name: ms-review
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/review}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:panama09}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8088

## Configuracion del cliente de Eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:ms-review}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

slr-assistant:
  app:
    frontend:
      url: ${FRONTEND_URL:http://localhost:3000}
  email:
    host: smtp.gmail.com
    port: 587
    username: seminario1fiec@gmail.com
    password: htgqxdxdfyreehxg